// Type declarations for CSS imports (normally generated by Expo on first `expo start`).
declare module '*.css';
declare module '*.module.css' {
  const classes: { [key: string]: string };
  export default classes;
}
